import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import Footer from '../components/partials/footer'
import Navbar from '../components/partials/navbar'
import { cn } from '@/lib/utils'
import Head from 'next/head'

const lato = Lato({
	subsets: ['latin'],
	weight: ['400', '700'],
})

export const metadata: Metadata = {
	title: 'A Journey',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="id" className="h-full">
			<Head>
				<title>A Journey</title>
				<meta
					name="description"
					content="A Little piece of my journey"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<body className={cn(lato.className, 'relative scroll-smooth')}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					themes={['light', 'dark', 'system']}
				>
					<Navbar />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
